---
title: "Team contract"
author: "Liza-Kemunto-Patrick"
output: github_document
---

## Goals:

* What are our team goals for this project?
* What do we want to accomplish?
* What skills do we want to develop or refine?

Learn how to manipulate data in new and efficient ways that strengthen the narrative we are sharing. 
Answer meaningful questions with data and create a story with powerful visualizations. 
Want to refine data manipulating skills and build visualizations that best convey our message with R. 
To create a compelling final project that reflects our data visualization skills in R and a tangible contribution to real world issues.


## Expectations:

* What do we expect of one another regarding attendance at meetings, participation, frequency of communication, quality of work, etc.?

Open and honest communication.
Make consistent effort to make progress even if it’s just an attempt to move the project forward.
We shall communicate on a regular basis to ensure that we stay on track with our set goals and deadlines. 
Schedule a brief weekly check-in to discuss work for the week and any major issues we’ve run into.
Actively participate in the project shared workload. 


## Policies & Procedures:

* What rules can we agree on to help us meet our goals and expectations?
Consequences:
* How will we address non-performance regarding these goals, expectations, policies and procedures?

Working together to communicate effectively and meet our team set deadlines in a timely manner. 
Sharing the workload equally such that we are all able to contribute fairly.
Clearly outline a person/people to complete specific parts of the project with an understanding that if there are issues that person/people are more than welcome to call on others for help.


## Consequences:

* How will we address non-performance regarding these goals, expectations, policies and procedures?

Have constructive feedback to ensure that every group member is aware of their responsibilities and contributions. 
Regroup if needed during weekly check-in, alter responsibilities and workloads accordingly.


## Signatures

* Each member should “sign” (you can just type out your name) at the bottom of the submission.

Kemunto Ongera
Patrick Bergin
Liza Dubinsky
